# Autogenerated wrapper script for JasPer_jll for i686-w64-mingw32
export imgcmp, imginfo, jasper, libjasper

using JpegTurbo_jll
JLLWrappers.@generate_wrapper_header("JasPer")
JLLWrappers.@declare_library_product(libjasper, "libjasper.dll")
JLLWrappers.@declare_executable_product(imgcmp)
JLLWrappers.@declare_executable_product(imginfo)
JLLWrappers.@declare_executable_product(jasper)
function __init__()
    JLLWrappers.@generate_init_header(JpegTurbo_jll)
    JLLWrappers.@init_library_product(
        libjasper,
        "bin\\libjasper.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        imgcmp,
        "bin\\imgcmp.exe",
    )

    JLLWrappers.@init_executable_product(
        imginfo,
        "bin\\imginfo.exe",
    )

    JLLWrappers.@init_executable_product(
        jasper,
        "bin\\jasper.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
